CREATE TABLE users (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100),
  email VARCHAR2(100) UNIQUE NOT NULL,
  password VARCHAR2(100) NOT NULL,
  role VARCHAR2(20)
);


CREATE USER isha ;
GRANT CONNECT, RESOURCE TO ffms_user;
-- Optionally give privileges to the table
GRANT ALL ON users TO ffms_user;
