CREATE TABLE Flights (
    flight_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_number VARCHAR2(20) NOT NULL,
    departure VARCHAR2(100),
    destination VARCHAR2(100),
    departure_time TIMESTAMP,
    arrival_time TIMESTAMP
);
