CREATE TABLE Menu (
    menu_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_name VARCHAR2(100) NOT NULL,
    price NUMBER(6, 2) NOT NULL,
    flight_id NUMBER,
    CONSTRAINT fk_flight_menu FOREIGN KEY (flight_id) REFERENCES Flights(flight_id)
);
