CREATE TABLE Order_Details (
    order_detail_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER,
    menu_id NUMBER,
    quantity NUMBER,
    subtotal NUMBER(8, 2),
    CONSTRAINT fk_detail_order FOREIGN KEY (order_id) REFERENCES Orders(order_id),
    CONSTRAINT fk_detail_menu FOREIGN KEY (menu_id) REFERENCES Menu(menu_id)
);
