CREATE TABLE Orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER,
    flight_id NUMBER,
    total_amount NUMBER(8, 2),
    order_status VARCHAR2(20),
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_order_customer FOREIGN KEY (customer_id) REFERENCES Customers(customer_id),
    CONSTRAINT fk_order_flight FOREIGN KEY (flight_id) REFERENCES Flights(flight_id)
);
