CREATE TABLE Transactions (
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER UNIQUE,
    payment_method VARCHAR2(50),
    payment_status VARCHAR2(20),
    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_transaction_order FOREIGN KEY (order_id) REFERENCES Orders(order_id)
);
